'use client';

import Link from 'next/link';
import { Check, ShieldCheck } from 'lucide-react';
import { useAlong } from './context';
import { ActionButton, PageHeading, Panel, PersonAvatar } from './shared';

export function ProfileScreen() {
  const { viewer, isAdmin, navigate, signOut, busy } = useAlong();
  return <><PageHeading title="Your profile" description="A little context helps people feel comfortable saying yes." /><div className="grid grid-cols-[minmax(0,1.3fr)_minmax(290px,.7fr)] gap-5 max-[760px]:grid-cols-1">
    <Panel><div className="flex items-center gap-3"><PersonAvatar initials={viewer.name.slice(0, 2).toUpperCase()} name={viewer.name} large /><div><strong className="block">{viewer.name}</strong><span className="text-xs text-muted-foreground">{viewer.email}</span></div></div><div className="my-6 grid gap-3 border-y border-border py-5"><div className="flex items-start gap-3"><ShieldCheck className="size-5 shrink-0 text-primary" /><div><strong className="block">Public meetups</strong><span className="text-[13px] text-muted-foreground">Keep first plans at public venues and agree on a clear meeting point.</span></div></div><div className="flex items-start gap-3"><Check className="size-5 shrink-0 text-primary" /><div><strong className="block">Show-up history</strong><span className="text-[13px] text-muted-foreground">Completed plans appear in My plans.</span></div></div></div><h2 className="mb-3 font-heading text-lg font-extrabold">Interests</h2>{viewer.interests.length ? <div className="flex flex-wrap gap-2">{viewer.interests.map((interest) => <span key={interest} className="rounded-full bg-accent px-3 py-1.5 text-xs font-bold text-accent-foreground"><span className="mr-1.5 inline-block size-1.5 rounded-full bg-pink" />{interest}</span>)}</div> : <p className="text-sm text-muted-foreground">You haven’t added interests yet.</p>}</Panel>
    <div className="grid content-start gap-4"><Panel><h2 className="mb-3 font-heading text-lg font-extrabold">Meet with care</h2><p className="mb-4 text-sm text-muted-foreground">Choose a public venue, share your plans with someone you trust, and leave if anything feels wrong.</p><ActionButton type="button" tone="secondary" onClick={() => navigate('explore')}>Browse public plans</ActionButton></Panel>{isAdmin && <Panel><h2 className="mb-3 font-heading text-lg font-extrabold">Admin workspace</h2><p className="mb-4 text-sm text-muted-foreground">Review reports, plans, and member activity.</p><Link href="/admin" className="inline-flex min-h-11 items-center rounded-xl bg-primary px-4 text-sm font-bold text-white hover:bg-forest">Open dashboard</Link></Panel>}<Panel><h2 className="mb-4 font-heading text-lg font-extrabold">Account</h2><ActionButton type="button" tone="secondary" className="w-full" disabled={busy} onClick={signOut}>Sign out</ActionButton></Panel></div>
  </div></>;
}
